kick_thresholds:
  - When 81 to 100 players online kick after 60 seconds
  - When 51 to 80  players online kick after 1000 seconds
  - When 1  to 51  players online kick after 5 seconds
warnings:
  - 1 1 second
  - 2 2 seconds
  - 3 3 seconds
  - 4 4 seconds
  - 5 5 seconds
  - 10 10 seconds
  - 60 1 minute
  - 300 5 minutes
  - 600 10 minutes
  - 1800 30 minutes
  - 3600 1 hour
kick_message: You were kicked due to inactivity